						<div class="top-content-up skin-border-color3">
							<!-- Logo  -->
							<a class="logo-link skin-font-color3 font-size-24px" href="<?php echo site_url(); ?>">
								<img src="<?php echo THEME_DIR ?>/images/logo.png" class="logo" alt="MusicFlow">
							</a>
							<!-- /Logo  -->
							<!-- Main menu  -->
							<ul class="main-menu regular">
								<!--<li id="menu-item-248"menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248><a href="" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">home</a>
									<!--<ul class="sub-menu">
										<li id="menu-item-249" class="current-menu-itemmenu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-249"><a href="" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home skin-font-color3">version 1 &#8211; slider</a></li>
										<li id="menu-item-251" class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom menu-item-251"><a href="" class=" menu-item menu-item-type-custom menu-item-object-custom skin-font-color3">version 2 &#8211; text &#038; buttons</a></li>
										<li id="menu-item-258" class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom menu-item-258"><a href="" class=" menu-item menu-item-type-custom menu-item-object-custom skin-font-color3">version 3 &#8211; just text</a></li>
										<li id="menu-item-259" class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom menu-item-259"><a href="" class=" menu-item menu-item-type-custom menu-item-object-custom skin-font-color3">version 4 &#8211; album wall</a></li>
										<li id="menu-item-260" class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom menu-item-260"><a href="" class=" menu-item menu-item-type-custom menu-item-object-custom skin-font-color3">version 5 &#8211; small header</a></li>
									</ul>
								</li>-->
								<li><a href="<?php echo site_url('noticias/actualidad/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Actualidad</a></li>
								<li><a href="<?php echo site_url('horarios/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Horarios</a></li>
								<li><a href="<?php echo site_url('programas/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Programas</a></li>
								<li><a href="<?php echo site_url('noticias/videos/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Videos</a></li>
								<li><a href="<?php echo site_url('noticias/galerias/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Galerías</a></li>
								<li><a href="<?php echo site_url('quienes-somos/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Quienes Somos</a></li>
								<li><a href="<?php echo site_url('contacto/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Contacto</a></li>
								<li><a href="<?php echo site_url('noticias/podcasts/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Podcats</a></li>
								<li><a href="<?php echo site_url('alianzas/') ?>" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-current bold">Alianzas</a></li>

							</ul>
							<!-- /Main menu  -->
							<!-- Mobile menu -->
							<span class="mobile-button icon font-size-46px skin-color-hover1">i</span>
							<ul class="mobile-menu regular">
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url(); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Inicio</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('noticias/actualidad/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Actualidad</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('horarios/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Horarios</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('programas/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Programas</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('noticias/actualidad/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Videos</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('noticias/actualidad/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Galerias</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('noticias/actualidad/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Quienes Somos</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('noticias/actualidad/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Contacto</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('noticias/actualidad/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Podcasts</a></li>
								<li class="skin-background-color4 skin-background-hover1 menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children menu-item-248"><a href="<?php echo site_url('noticias/actualidad/'); ?>" class=" menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home current-menu-ancestor current-menu-parent menu-item-has-children skin-font-color3 skin-background-color1">Alianzas</a></li>

							</ul>
							<!-- /Mobile menu  -->
						</div>
						<div class="top-content-down skin-border-color3">
							<!-- Social  -->
							<ul class="social">
								<li class="skin-background-color1 skin-background-hover3" ><a href=""><img src="<?php echo THEME_DIR ?>/icons/facebook.svg" alt="social"></a></li>
								<li class="skin-background-color1 skin-background-hover3" ><a href=""><img src="<?php echo THEME_DIR ?>/icons/twitter.svg" alt="social"></a></li>
								<li class="skin-background-color1 skin-background-hover3" ><a href=""><img src="<?php echo THEME_DIR ?>/icons/youtube.svg" alt="social"></a></li>
							</ul>
							<!-- /Social  -->
						</div>